version: '3.8'
services:
  app:
    image: spring-boot-keycloak-docker-postgres:latest
    container_name: web-app
    ports:
      - "8088:8088"
    depends_on:
      - postgresql
      - keycloak
#    healthcheck:
#      test: curl -f http://localhost:8088/demo/profile || exit 1
#      interval: 1m
#      timeout: 10s
#      retries: 2
  postgresql:
    image: docker.io/bitnami/postgresql:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
  #KEYCLOAK
  #login: user
  #password: bitnami
  #docs: https://hub.docker.com/r/bitnami/keycloak
  keycloak:
    image: docker.io/bitnami/keycloak:latest
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_CREATE_ADMIN_USER=true
    depends_on:
      - postgresql
    volumes:
      - './mynewtheme:/opt/bitnami/keycloak/themes/mynewtheme'
volumes:
  postgresql_data:
    driver: local